// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMCx9L1mKIBGgkA2HYqRjAtNqwwDX6Jvw',
    appId: '1:186587038018:web:49e00e59f66664de3048db',
    messagingSenderId: '186587038018',
    projectId: 'trees-app-841af',
    authDomain: 'trees-app-841af.firebaseapp.com',
    storageBucket: 'trees-app-841af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADGmyQiNL73raUj4ImgTVdTaBDgH09szU',
    appId: '1:186587038018:android:20966dd1786872273048db',
    messagingSenderId: '186587038018',
    projectId: 'trees-app-841af',
    storageBucket: 'trees-app-841af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Kbkbt0Cw9Gk-s6qi2JcugBamHkwqAok',
    appId: '1:186587038018:ios:891a2d049bbc83933048db',
    messagingSenderId: '186587038018',
    projectId: 'trees-app-841af',
    storageBucket: 'trees-app-841af.appspot.com',
    iosBundleId: 'com.example.treesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Kbkbt0Cw9Gk-s6qi2JcugBamHkwqAok',
    appId: '1:186587038018:ios:35d7b5f76ae9b19e3048db',
    messagingSenderId: '186587038018',
    projectId: 'trees-app-841af',
    storageBucket: 'trees-app-841af.appspot.com',
    iosBundleId: 'com.example.treesProject.RunnerTests',
  );
}
