// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPamFlchV4WYHPoJgFUTZIceZZTNnTzQ',
    appId: '1:243428541553:web:76cb61a105723fe521c7d0',
    messagingSenderId: '243428541553',
    projectId: 'treesapp-c18cb',
    authDomain: 'treesapp-c18cb.firebaseapp.com',
    storageBucket: 'treesapp-c18cb.appspot.com',
    measurementId: 'G-QF057510FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyhV-M124Zn9yxAUCCeC1sBFVlKApVAbk',
    appId: '1:243428541553:android:0bf73a37fb56399d21c7d0',
    messagingSenderId: '243428541553',
    projectId: 'treesapp-c18cb',
    storageBucket: 'treesapp-c18cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFF2LrPP8VvXvSw44MKaPR9DaGBkm6j0',
    appId: '1:243428541553:ios:472dd81fab51a3a521c7d0',
    messagingSenderId: '243428541553',
    projectId: 'treesapp-c18cb',
    storageBucket: 'treesapp-c18cb.appspot.com',
    iosBundleId: 'com.example.treesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXWAMC1kRba9Ttm1YIBKh9srN5ltWybv8',
    appId: '1:166751578555:ios:0420209a53998e229dbc9e',
    messagingSenderId: '166751578555',
    projectId: 'trees-bf876',
    storageBucket: 'trees-bf876.appspot.com',
    iosBundleId: 'com.example.treesProject.RunnerTests',
  );
}