// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsMB5_4riqWPBQ_eeMqJcx6fTUIY_FBwM',
    appId: '1:166751578555:web:fdd60f66cc96ed279dbc9e',
    messagingSenderId: '166751578555',
    projectId: 'trees-bf876',
    authDomain: 'trees-bf876.firebaseapp.com',
    storageBucket: 'trees-bf876.appspot.com',
    measurementId: 'G-R3S81S95TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOkHYVuQm63wABUq0F0cR_oP0p_caJ3Gw',
    appId: '1:166751578555:android:cc96b9ec1de3c5ae9dbc9e',
    messagingSenderId: '166751578555',
    projectId: 'trees-bf876',
    storageBucket: 'trees-bf876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWAMC1kRba9Ttm1YIBKh9srN5ltWybv8',
    appId: '1:166751578555:ios:920b52eeb4c0be0a9dbc9e',
    messagingSenderId: '166751578555',
    projectId: 'trees-bf876',
    storageBucket: 'trees-bf876.appspot.com',
    iosBundleId: 'com.example.treesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXWAMC1kRba9Ttm1YIBKh9srN5ltWybv8',
    appId: '1:166751578555:ios:0420209a53998e229dbc9e',
    messagingSenderId: '166751578555',
    projectId: 'trees-bf876',
    storageBucket: 'trees-bf876.appspot.com',
    iosBundleId: 'com.example.treesProject.RunnerTests',
  );
}
